config/routes.rb
RedditClone::Application.routes.draw do

  resources :users
  resource :session
  resources :subs
  resources :links
  resources :comments

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :link_id, :parent_comment_id, :user_id

  validates :body, :link_id, :user_id, :presence => true

  belongs_to :link
  belongs_to :user
  belongs_to :parent_comment,
  :class_name => "Comment",
  :foreign_key => :parent_comment_id,
  :primary_key => :id

end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :description, :sub_id, :submitter, :title, :url
  attr_reader :comment_hash

  validates :sub, :submitter, :title, :url, :presence => true

  has_many :comments
  belongs_to :sub
  belongs_to :submitting_user,
  :class_name => "User",
  :foreign_key => :submitter,
  :primary_key => :id

  def comments_by_parent_id
    @indents = 0
    @comment_hash = Hash.new { |h,k| h[k] = [] }

    self.comments.each do |comment|
      @comment_hash[comment.parent_comment_id] << comment
    end
    @comment_hash
  end

end

app/models/sub.rb
class Sub < ActiveRecord::Base
  attr_accessible :moderator, :name, :links_attributes

  validates :name, :uniqueness => true
  validates :moderator, :name, :presence => true

  has_many :links, :inverse_of => :sub

  belongs_to :moderating_user,
  :class_name => "User",
  :foreign_key => :moderator,
  :primary_key => :id

  accepts_nested_attributes_for :links, reject_if: :reject_link

  def reject_link(attributed)
    attributed['title'].blank? && attributed['url'].blank?
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :password, :username
  attr_reader :password
  before_validation :ensure_session_token, :on => :create

  validates :password_digest, :username, :session_token, :presence => true
  validates :username, :session_token, :uniqueness => true
  validates :password, :length => { :minimum => 6 }, :if => :password_present?

  has_many :subs,
  :class_name => "Sub",
  :foreign_key => :moderator,
  :primary_key => :id

  has_many :links,
  :class_name => "Link",
  :foreign_key => :submitter,
  :primary_key => :id

  has_many :comments

  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end

  def self.generate_token
    SecureRandom.urlsafe_base64(16)
  end

  def self.find_by_credentials(user, pw)
    user = User.find_by_username(user)

    user if user && user.is_password?(pw)
  end

  def is_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end

  def ensure_session_token
    self.session_token = self.class.generate_token
  end

  def reset_session_token
    ensure_session_token
  end

  def password_present?
    !self.password.nil?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include ApplicationHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    #USELESS.
  end

  def new
    @comment = Comment.new
    render :new
  end

  def create
    @comment = Comment.new(params[:comment])

    if @comment.save
      redirect_to link_url(@comment.link)
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  def show
    @comment = Comment.find(params[:id])
    render :show
  end

  def edit
    @comment = Comment.find(params[:id])
    render :edit
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update_attributes(params[:comment])
      redirect_to link_url(@comment.link)
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @link = @comment.link
    @comment.destroy
    redirect_to link_url(@link)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @links = Link.all
    render :index
  end

  def new
    render :new
  end

  def create
    @link = Link.new(params[:link])

    if @link.save
      redirect_to link_url(@link)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def edit
    @link = Link.find(params[:id])
    render :edit
  end

  def update
    @link = Link.find(params[:id])

    if @link.update_attributes(params[:link])
      redirect_to link_url(@link)
    else
      flash.now[:errors] = ["Cannot find this link."]
      render :edit
    end
  end

  def destroy
    @link = Link.find(params[:id])
    @link.destroy
    redirect_to links_url
  end

  def show
    @link = Link.find(params[:id])
    @comments = @link.comments_by_parent_id

    render :show
  end

  def print_comment(key)
    @comment_hash[key].each do |comment|
      spaces = @indents.times { print "    "}
      puts "#{spaces}#{comment.user.username} says: #{comment.body}"
      @indents += 1
      print_comment(comment.id)
      @indents = 0
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(
    params[:user][:username],
    params[:user][:password])

    if @user
      login!(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = ['Error upon login.  Try again.']
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  def index
    @subs = Sub.all
    render :index
  end

  def new
    @sub = Sub.new
    5.times { @sub.links.build }
    render :new
  end

  def create
    @sub = Sub.new(params[:sub])
    # @sub.links.new(params[:sub][:links].values)

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = Sub.find(params[:id])

    if @sub.update_attributes(params[:sub])
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def destroy
    @sub = Sub.find(params[:id])
    @sub.destroy
    redirect_to subs_url
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      login!(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login!(user)
    user.reset_session_token
    user.save!
    session[:session_token] = user.session_token
  end

  def logout!
    current_user.reset_session_token
    current_user.save!
    session[:session_token] = nil
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:errors] %>
  <ul><% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %></ul>
<% end %>

<%= yield %>


<% if logged_in? %>
  <%= "Hello, #{current_user.username}"%>
  <%= button_to "Log Out", session_url, :method => :delete %>
<% else %>
  <%= link_to "Log In", new_session_url%>
<% end %>

</body>
</html>

app/views/links/create.html.erb
<h1>Links#create</h1>
<p>Find me in app/views/links/create.html.erb</p>

app/views/links/destroy.html.erb
<h1>Links#destroy</h1>
<p>Find me in app/views/links/destroy.html.erb</p>

app/views/links/edit.html.erb
<h1>Edit Link</h1>

<form action="<%= link_url(@link)%>" method="POST">
  <input type="hidden" name="_method" value="PUT">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="link_sub_id">Sub</label>
  <select name="link[sub_id]" id="link_sub_id">
    <% Sub.all.each do |sub| %>
      <option value="<%= sub.id %>" <%= "selected" if sub.id == @link.sub_id%>><%= sub.name %></option>
    <% end %>
  </select>
  <br>

  <label for="link_title">Title</label>
  <input type="text" id="link_title" name="link[title]" value="<%= @link.title %>">
  <br>

  <label for="link_url">URL</label>
  <input type="text" id="link_url" name="link[url]" value="<%= @link.url %>">
  <br>

  <label for="link_description">Description (Optional)</label>
  <input type="text" id="link_description" name="link[description]" value="<%= @link.description %>">
  <br>

  <input type="submit" value="Edit">

</form>

app/views/links/index.html.erb
<h1>Links#index</h1>
<p>Find me in app/views/links/index.html.erb</p>

app/views/links/new.html.erb
<h1>Submit New Link</h1>

<form action="/links" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <input type="hidden" name="link[submitter]" value="<%= current_user.id%>">

  <label for="link_sub_id">Sub</label>
  <select name="link[sub_id]" id="link_sub_id">
    <% Sub.all.each do |sub| %>
      <option value="<%= sub.id %>"><%= sub.name %></option>
    <% end %>
  </select>
  <br>

  <label for="link_title">Title</label>
  <input type="text" id="link_title" name="link[title]">
  <br>

  <label for="link_url">URL</label>
  <input type="text" id="link_url" name="link[url]">
  <br>

  <label for="link_description">Description (Optional)</label>
  <input type="text" id="link_description" name="link[description]">
  <br>
  <input type="submit" value="Create">
</form>

app/views/links/show.html.erb
<h1><%= @link.title %></h1>
<!-- start from here. -->
<%= "Submitted by: #{@link.submitting_user.username}" %>
<br>
<%=link_to @link.url, @link_url %>
<br>
<%= @link.description %>
<br>
<br>
<% if current_user.id == @link.submitting_user.id %>
  <%= link_to("Edit Link Properties", edit_link_url(@link)) %>
<% end %>
<br>
<br>
<% if @comments %>
  <%= @link.print_comment(nil) %>
<% end %>
<br>
<br>

app/views/links/update.html.erb
<h1>Links#update</h1>
<p>Find me in app/views/links/update.html.erb</p>

app/views/subs/create.html.erb
<h1>Subs#create</h1>
<p>Find me in app/views/subs/create.html.erb</p>

app/views/subs/destroy.html.erb
<h1>Subs#destroy</h1>
<p>Find me in app/views/subs/destroy.html.erb</p>

app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<form action="<%= sub_url(@sub) %>" method="POST">
  <input type="hidden" name="_method" value="PUT">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="sub[moderator]" value="<%= current_user.id%>">
  <label for="sub_name">Name</label>
  <input type="text" id="sub_name" name="sub[name]" value="<%= @sub.name %>">
  <input type="submit" value="Submit Edits">
</form>

app/views/subs/index.html.erb
<h1>All Subs</h1>

<% if @subs %>
  <% @subs.each do |sub| %>
    <li><%= link_to(sub.name, sub_url(sub)) %></li>
  <% end %>
<% end %>

app/views/subs/new.html.erb
<h1>Create New Sub</h1>

<form action="/subs" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="sub[moderator]" value="<%= current_user.id%>">
  <label for="sub_name">Name</label>
  <input type="text" id="sub_name" name="sub[name]">
  <br>
  <% @sub.links.each do |link| %>
  <input type="hidden" name="sub[links_attributes][<%= link.object_id %>][submitter]" value="<%= current_user.id %>">
  <label for="link_title<%= link.object_id%>">Title</label>
  <input type="text" id="link_title<%= link.object_id%>" name="sub[links_attributes][<%= link.object_id %>][title]">
  <br>
  <label for="link_url<%= link.object_id%>">URL</label>
  <input type="text" id="link_url<%= link.object_id%>" name="sub[links_attributes][<%= link.object_id %>][url]">
  <br>
  <label for="link_description<%= link.object_id%>">Description(Optional)</label>
  <input type="text" id="link_description<%= link.object_id%>" name="sub[links_attributes][<%= link.object_id %>][description]">
  <br>
  <% end %>
  <input type="submit" value="Create Sub">
</form>

app/views/subs/show.html.erb
<h1>Links for <%= @sub.name %></h1>

<%= "Moderated by: #{@sub.moderating_user.username}" %>
<br>
<% if @sub.links %>
  <ul>
  <% @sub.links.each do |link| %>
    <li><%= link_to(link.title, link_url(link)) %></li>
  <% end %>
  </ul>
<% end %>
<br>
<br>
<%= link_to("Submit a new link", new_link_url)%>
<br>
<br>
<% if current_user.id == @sub.moderating_user.id %>
  <%= link_to("Edit Sub Properties", edit_sub_url(@sub)) %>
<% end %>
<br>
<br>

app/views/subs/update.html.erb
<h1>Subs#update</h1>
<p>Find me in app/views/subs/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>


<form action="/users" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="user_username">Username</label>
  <input type="text" id="user_username" name="user[username]">
  <br>
  <label for="user_password">Password</label>
  <input type="password" id="user_password" name="user[password]">
  <br>
  <input type="submit" value="Sign Up">
</form>